export interface PresetQuestion {
  id: number;
  text: string;
}

/**
 * Flat pool of 150 relational questions with categories removed.
 * This serves as the raw dictionary for the application's randomization engine.
 */
export const PRESET_QUESTIONS: PresetQuestion[] = [
  { id: 1, text: "What color are my eyes?" },
  { id: 2, text: "What is my least favorite season of the year?" },
  { id: 3, text: "What’s my favorite season?" },
  { id: 4, text: "What is my favorite thing in my house?" },
  { id: 5, text: "Where do I like to shop the most?" },
  { id: 6, text: "Who is the most shy person I know?" },
  { id: 7, text: "What’s my favorite book or author?" },
  { id: 8, text: "What type of music do I like best?" },
  { id: 9, text: "What type of music would you never catch me listening to?" },
  { id: 10, text: "Which chore do I hate doing the most?" },
  { id: 11, text: "What’s my favorite color?" },
  { id: 12, text: "What is my favorite day of the week?" },
  { id: 13, text: "How do I like to spend my free time?" },
  { id: 14, text: "Android or iPhone?" },
  { id: 15, text: "What is my favorite style?" },
  { id: 16, text: "Where is my favorite place to read?" },
  { id: 17, text: "What is my favorite smell?" },
  { id: 18, text: "Do I have a specific bedtime?" },
  { id: 19, text: "What’s my favorite thing to do at the park?" },
  { id: 20, text: "What show do I like to watch the most?" },
  { id: 21, text: "Who would I be if I could be any character in a book, TV show, or movie?" },
  { id: 22, text: "What are my primary hobbies?" },
  { id: 23, text: "Am I right or left-handed?" },
  { id: 24, text: "Do I snore?" },
  { id: 25, text: "Who was my favorite teacher growing up?" },
  { id: 26, text: "What is my very first memory?" },
  { id: 27, text: "Did I have braces growing up?" },
  { id: 28, text: "Who was my childhood best friend?" },
  { id: 29, text: "Did I believe in imaginary friends?" },
  { id: 30, text: "What was my favorite stuffed animal as a child?" },
  { id: 31, text: "What was my deepest childhood fear?" },
  { id: 32, text: "What sports did I play as a child?" },
  { id: 33, text: "What is my worst childhood memory?" },
  { id: 34, text: "Was I a 'play-in-the-mud' kid or a 'build-a-fort' kid?" },
  { id: 35, text: "What was my favorite subject in school?" },
  { id: 36, text: "What was I better at: tag or hide-and-seek?" },
  { id: 37, text: "What was my favorite snack as a child?" },
  { id: 38, text: "What did I think I could get away with as a child?" },
  { id: 39, text: "Was I good at school when I was younger?" },
  { id: 40, text: "Who was my childhood pet?" },
  { id: 41, text: "Who in my family am I most similar to?" },
  { id: 42, text: "How many pets do I ideally want?" },
  { id: 43, text: "Who do I look most like in my family?" },
  { id: 44, text: "What is my favorite thing about my family?" },
  { id: 45, text: "What was my personality like as a small child?" },
  { id: 46, text: "Am I close with my family?" },
  { id: 47, text: "Do I want a large family in the future?" },
  { id: 48, text: "Who is my favorite cousin?" },
  { id: 49, text: "Do I genuinely enjoy spending time with my family?" },
  { id: 50, text: "What is my middle name?" },
  { id: 51, text: "What do I consider the true meaning of family?" },
  { id: 52, text: "What was my least favorite thing to do with family growing up?" },
  { id: 53, text: "What was my favorite thing to do with family growing up?" },
  { id: 54, text: "What is my family nickname?" },
  { id: 55, text: "Do I look more like my mom or my dad?" },
  { id: 56, text: "Was I the favorite grandchild?" },
  { id: 57, text: "Do I want children, pets, or both?" },
  { id: 58, text: "Was I raised in a strict household?" },
  { id: 59, text: "What specific chores did I have to do growing up?" },
  { id: 60, text: "When was the last time I actually went to a family reunion?" },
  { id: 61, text: "Do I have a favorite flavor of ice cream?" },
  { id: 62, text: "How do I feel about waffles?" },
  { id: 63, text: "What is my favorite food to eat in the whole world?" },
  { id: 64, text: "Do I have a favorite vegetable?" },
  { id: 65, text: "What’s my favorite type of pizza?" },
  { id: 66, text: "If I could only eat one type of cookie for the rest of my life, what would it be?" },
  { id: 67, text: "Do I prefer savory foods or sweets?" },
  { id: 68, text: "What’s my favorite type of cheese?" },
  { id: 69, text: "Am I a wine, beer, or non-alcoholic drink person?" },
  { id: 70, text: "Do I prefer to cook at home or eat out?" },
  { id: 71, text: "What restaurant is my absolute favorite?" },
  { id: 72, text: "What’s my favorite candy?" },
  { id: 73, text: "What dish am I best at making myself?" },
  { id: 74, text: "Do I prefer to bake or to cook?" },
  { id: 75, text: "Can I properly operate a grill?" },
  { id: 76, text: "Could you ever see me field-dressing an animal?" },
  { id: 77, text: "Do I actually like to grocery shop?" },
  { id: 78, text: "What single meal could I eat every single day?" },
  { id: 79, text: "Do I have any food allergies or intolerance?" },
  { id: 80, text: "Where is my favorite place to physically eat food? (e.g., bed, couch, table)" },
  { id: 81, text: "If I had to choose any place in the world to live, where would it be?" },
  { id: 82, text: "Where do I feel most relaxed?" },
  { id: 83, text: "Where did I travel to right after I graduated high school?" },
  { id: 84, text: "Have I ever been on a cruise ship?" },
  { id: 85, text: "What is the farthest distance I’ve ever driven in a single road trip?" },
  { id: 86, text: "Have I ever been out of the country?" },
  { id: 87, text: "Do I genuinely like to hike?" },
  { id: 88, text: "Do I travel on a strict budget, or go all out on luxury options?" },
  { id: 89, text: "Where have I always wanted to go, but have never been yet?" },
  { id: 90, text: "When I travel, how many suitcases do I typically pack?" },
  { id: 91, text: "Do I save up cash for vacations, or put them on credit and pay it off later?" },
  { id: 92, text: "Do I pack all possible essentials, or prefer to buy them when I arrive?" },
  { id: 93, text: "What is my absolute favorite vacation that I’ve ever taken?" },
  { id: 94, text: "Do I currently have active plans to travel anywhere soon?" },
  { id: 95, text: "Where is one place I never want to travel to?" },
  { id: 96, text: "Who was my very first romantic crush?" },
  { id: 97, text: "Do I fundamentally prefer to be single or in a relationship?" },
  { id: 98, text: "How long was my longest relationship?" },
  { id: 99, text: "Who was my most meaningful relationship with?" },
  { id: 100, text: "Where did my first kiss take place?" },
  { id: 101, text: "Who was my very first kiss?" },
  { id: 102, text: "Who usually says 'I love you' first: me or the other person?" },
  { id: 103, text: "What is my primary love language?" },
  { id: 104, text: "Am I overtly affectionate or more reserved/passive?" },
  { id: 105, text: "What type of person do you realistically see me marrying?" },
  { id: 106, text: "How long did my shortest relationship last?" },
  { id: 107, text: "Did I date anyone seriously in grade school?" },
  { id: 108, text: "How do I honestly feel about the concept of love?" },
  { id: 109, text: "What’s the longest continuous stretch of time I’ve been single?" },
  { id: 110, text: "Do I typically make the first move, or wait for the other person?" },
  { id: 111, text: "What did I want to be when I grew up when I was little?" },
  { id: 112, text: "Who is my absolute work best friend?" },
  { id: 113, text: "How would you honestly describe my work ethic?" },
  { id: 114, text: "What is my normal weekly work schedule?" },
  { id: 115, text: "Do I take overtime hours when they are made available?" },
  { id: 116, text: "Do you know the neighborhood or street address of my workplace?" },
  { id: 117, text: "Do you know the exact name of the company I work for?" },
  { id: 118, text: "What is my exact job title?" },
  { id: 119, text: "What core duties do I actually perform during the day at work?" },
  { id: 120, text: "What would my absolute dream job be?" },
  { id: 121, text: "Am I working in the professional field that I most want to be in?" },
  { id: 122, text: "Am I an hourly wage earner or a salaried employee?" },
  { id: 123, text: "What do I approximately make per hour or annually?" },
  { id: 124, text: "Do I work full-time or part-time hours?" },
  { id: 125, text: "Does my job offer benefits, and am I happy with them?" },
  { id: 126, text: "Am I strictly for or against frilly decorative toothpicks?" },
  { id: 127, text: "What is the absolute first thing I do when I wake up in the morning?" },
  { id: 128, text: "What is the very last thing I do before closing my eyes at night?" },
  { id: 129, text: "What size clothing do I typically wear?" },
  { id: 130, text: "What specific thing do I do that always makes you laugh?" },
  { id: 131, text: "What type of things reliably make me laugh?" },
  { id: 132, text: "What strange object would you reliably find in my bag, wallet, or backpack?" },
  { id: 133, text: "If I could choose any classical superpower, which one would I pick?" },
  { id: 134, text: "What is my absolute least favorite noise in the world?" },
  { id: 135, text: "Which Hogwarts house am I officially sorted into?" },
  { id: 136, text: "What historical time period would I choose to live in if forced to time travel?" },
  { id: 137, text: "What is the most entirely random thing I’ve ever done on a whim?" },
  { id: 138, text: "Where exactly did we meet for the first time, and how?" },
  { id: 139, text: "Do I consider myself more of a Monica, Rachel, or Phoebe?" },
  { id: 140, text: "Am I characteristically more like Ross, Chandler, or Joey?" },
  { id: 141, text: "What model of car did I originally learn how to drive in?" },
  { id: 142, text: "What is the weirdest niche interest or hobby that I am secretly into?" },
  { id: 143, text: "Would I rather jump out of a plane skydiving or go deep cave spelunking?" },
  { id: 144, text: "If I could magically sprout wings, would they look like bat wings or bird wings?" },
  { id: 145, text: "Do I prefer over-ear headphones or low-profile earbuds?" },
  { id: 146, text: "Who is my favorite anime or animated character?" },
  { id: 147, text: "Do I derive more joy from giving gifts or receiving them?" },
  { id: 148, text: "What is my default preferred sleeping position?" },
  { id: 149, text: "Am I naturally good at mental math?" },
  { id: 150, text: "Have I ever accidentally pooped my pants as an adult?" }
];

/**
 * SSR-safe pseudo-random array sampler.
 * Extracts a balanced random slice of unselected options from our primary matrix.
 */
export function sampleRandomQuestions(count: number): PresetQuestion[] {
  const shuffled = [...PRESET_QUESTIONS].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, Math.round(Math.max(10, Math.min(count, 20))));
}